### ISSUE TITLE
[FE-8]Stworzenie listy wydarzeń

### ISSUE THREAD

**Issue by LukaszStaniszewski** [akademia-envelo-3/MELO-front#10]
### Story
Jako użytkownik chcę widzieć listę kart z wydarzeniami. 

### Dodatkowe informacje
Na tym ekranie nie uwzględniamy infinite scrolla. Fetchujemy domyślnie 12 kart powyżej maksymalnego breakpointu, poniżej fetchujemy 8.

### Makiety
[Widok listy wydarzeń](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=314%3A9859&t=nVXt6HRhtqq5qy22-4)
[break points](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=369%3A9972&t=nVXt6HRhtqq5qy22-4)

### Taski blokujące
 - #8 
 - #1 
 - #2 
### Taski powiązane
- #4 
- #7 
### Endpointy
- [lista eventow](https://ibb.co/1vBj1sW)

### Kryteria akceptacji
1. Jako użytkownik chcę widzieć listę wydarzeń z różnymi tłami.
2. Lista ma być responsywna, dostosowywać ilość wyświetlanych kart zależnie od szerokości ekranu.
~~3. Powyżej maksymalnego breakpointu ma się pobierać 12 kart, dla niższych breakpointów 8 kart.~~

**Comment by dominikapap** [comment]
[preview](https://fe-8-event-list--melo-envelo.netlify.app/)

**Comment by dominikapap** [comment]
Aktualizacja punktu 3, pobieramy 12 kart niezależnie od breakpointu.
