### ISSUE TITLE
[FE-14]Stworzenie serwisu event pobierajacego dane wymagane do wyświetlenie eventów

### ISSUE THREAD

**Issue by LukaszStaniszewski** [akademia-envelo-3/MELO-front#17]
### Dodatkowe informacje
Należy stworzyć serwis event i dodać do niego metody fetchujące liste eventów oraz szczegóły eventu.

#### Lista eventow
get /event
[EventToDisplayOnList](https://ibb.co/Qrcn6DG).
#### Szczegóły eventu
get /eventDetails?id=id
[EventDetailsDTO](https://ibb.co/sqjP17V).

### Kryteria akceptacji
1. Serwis znajduje się w module event
2. Metoda do pobierania listy eventów, poprawnie pobiera liste eventów.
3. Metoda do pobierania szczegółów eventu poprawnie  pobiera szczegóły eventu.
4. Wynik pobrania powinien być zapisany w state serwisu który jest Observablem.
5. Działający Interceptor który dodaje podstawe url do requestu - http//:localhost:300

**Comment by abdevworks** [comment]
Kryteria akceptacji
- [x] 1. Serwis znajduje się w module event
- [x]  2. Metoda do pobierania listy eventów, poprawnie pobiera liste eventów.
- [x]  3. Metoda do pobierania szczegółów eventu poprawnie pobiera szczegóły eventu.
- [x]  4. Wynik pobrania powinien być zapisany w state serwisu który jest Observablem.
- [x]  5. Działający Interceptor który dodaje podstawe url do requestu - http//:localhost:300

Testy ok. 
Do poprawy literówka nazwy pliku 'contants' w module shared. Powinno być 'constants'.
