### ISSUE TITLE
[FE-15] Stworzenie strony 404

### ISSUE THREAD

**Issue by dominikapap** [akademia-envelo-3/MELO-front#19]
### Dodatkowe Informacje

Wprowadzony przez użytkownika adres podstrony jest nieprawidłowy lub system nie może odnaleźć danej strony. Na tym etapie strona nie musi posiadać navbara i sidebara. 

### Makiety 
[mobile](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=454%3A9841&t=PojAXxbYIEKkm7Bq-0)
[desktop](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=457%3A9907&t=PojAXxbYIEKkm7Bq-0)

### Kryteria akceptacji

1. Wygląd jest zgodny z makietą 
2. Strona jest responsywna 
3. Na stronie wyświetlona jest informacja, że dana strona nie została odnaleziona
4. Na stronie wyświetlona jest grafika z makiety
5. Na stronie jest przycisk przekierowywujacy na stronę główną
6. Strona ma tło zgodne z makietą

**Comment by dominikapap** [comment]
Task blokujący 
#3

**Comment by dominikapap** [comment]
ogólna logika i style wprowadzone, czekam z dokończeniem taska na wypchnięcie do repozytorium design system

**Comment by dominikapap** [comment]
wygląd przycisku zostanie podmieniony w kolejnym tasku

**Comment by PawelJurga** [comment]
@dominikapap podrzuć link do taska, to popatrzę w wolnej chwili :)

**Comment by dominikapap** [comment]
@PawelJurga linki poniżej 

[preview ogólny](https://fe-15-page-not-found--melo-envelo.netlify.app/)

[preview ze stroną nieznalezioną](https://fe-15-page-not-found--melo-envelo.netlify.app/cos)

**Comment by PawelJurga** [comment]
@dominikapap jak skończysz oznacz mnie do testów :)

**Comment by PawelJurga** [comment]
- [ ]  Wygląd jest zgodny z makietą

  - **cień grafiki _"strona której szukasz nie istnieje"_ należy dopasować do widoku strony z zachowaniem marginesów i miejsca na nevbar**  

- [x]  Strona jest responsywna

    

- [x] Na stronie wyświetlona jest informacja, że dana strona nie została odnaleziona

   

- [x]  Na stronie wyświetlona jest grafika z makiety

   
~~- [ ]  Na stronie jest przycisk przekierowywujacy na stronę główną~~  **zostanie dodane w innym tasku**

   

- [ ]  Strona ma tło zgodne z makietą
-   **tło w wersji mobilnej nie jest zgodne z widokiem makiety - należy je wycentrować** 



![Image](https://user-images.githubusercontent.com/121928858/213375179-ca288271-8e9e-4ed0-92cb-069c0b166779.png)

**Comment by PawelJurga** [comment]
**RETEST**
 
 - [x]  - [ ] Wygląd jest zgodny z makietą

- **Makieta, która jest wyrocznią dla tego taska posiadała nieścisłości. Po konsultacji w zepole FrontEnd zdecydowano poprawić i dostosować makietę do widoku utworzonego w ramach tego zadania.** 

- [x]  Strona ma tło zgodne z makietą

- **tło widoku poprawiono**

 **Testy wykazały, że kompletny widok (Pod dodaniu do niego Nevbar) będzie User frendly, ponieważ strzałka powrotu zostanie umieszczona w najlepszym miejscu urządzenia mobilnego dla obsługi kciukiem.**

**Rekomenduję zakończenie taska**
