### ISSUE TITLE
[FE-17] Stworzenie widoku z formularzem dla nowego koła zainteresowań

### ISSUE THREAD

**Issue by rafalfuz** [akademia-envelo-3/MELO-front#22]
Jako użytkownik chciałbym po wybraniu opcji utworzenia nowego koła zainteresowań moc zobaczyć widok z formularzem. 

Makiety: 

[mobile](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=319%3A10266&t=mlP3GHhN8z0TTbUw-4)
[errors](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=319%3A11204&t=qTdwdFk6Ml2I8k71-0)
[errors2](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=319%3A11091&t=FSxIwueTKEeTfQva-0)
[desktop](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=503%3A10142&t=FSxIwueTKEeTfQva-0)

Taski powiązane: 
Widok wyniku wysłania formularza
Kryteria akceptacji: 

Kryteria akceptacji: 

1. Widok zgodny z makietami 
2. Button “Back” przenosi do widoku wszystkich kół 
3. Pola formularza po powrocie zachowują wartości wcześniej uzupełnione (formularz się nie resetuje) 
4. Pole “Nazwa kola” oraz “opis”, są wymagane, jeżeli użytkownik ich nie wypełni style inputów zmiana się zgodnie z makietami oraz zostanie wyświetlony komunikat o koniczności ich wypełniania 
5. Pole Nazwa koła nie może przekroczyć 255 znaków, w przeciwnym wypadku zostanie wyświetlony komunikat informujący o tym 
6. Pole Opis nie może przekroczyć 4000 znaków, w przeciwnym wypadku zostanie wyświetlony komunikat informujący o tym 
7. Kursor zmienia się na pointer po najechaniu na Button “Utwórz”

**Comment by dominikapap** [comment]
[preview na netlify](https://fe-17-unit-form--melo-envelo.netlify.app/units/new-unit)

**Comment by rafalfuz** [comment]
![Image](https://user-images.githubusercontent.com/71282094/214792203-d4576a28-ab68-4bfc-8543-af56ecbfdff0.png)


Kolor z backgroundu zmienia sie po wybraniu opcji z autouzupelniania

**Comment by rafalfuz** [comment]
![Image](https://user-images.githubusercontent.com/71282094/214792716-6a702b1c-9564-4e8c-94eb-83a1c0fcf0f9.png)

Textarea mozna rozciagnac poza okno formularza

**Comment by dominikapap** [comment]
@rafalfuz poprawione, prośba o sprawdzenie czy teraz jest ok

**Comment by rafalfuz** [comment]
Jest ok
