### ISSUE TITLE
[FE-16] Stworzenie widoku wyniku wysłania formularza

### ISSUE THREAD

**Issue by rafalfuz** [akademia-envelo-3/MELO-front#23]
Jako użytkownik/admin chciałbym zobaczyć ekran informujący mnie o wyniku wysłania mojego formularza

Informacje dodatkowe: 

Rezultat wysłania formularza dotyczącego utworzenie kola zainteresowań, utworzenie eventu, utworzenie ankiety oraz dla zmiany organizatora kola i eventu przez admina. Task dotyczy utworzenia wyglądu poszczególnych ekranów

Makiety:
https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=319%3A11068&t=pT77RV7nXD0FiW7g-4 
https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=319%3A11119&t=pT77RV7nXD0FiW7g-4 
https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=315%3A11129&t=pT77RV7nXD0FiW7g-4 

Taski powiązane: 
- Widok z formularzem utworzenia koła zainteresowań
- Widok z formularzem utworzenia eventu
- Widok z formularzem zmiany organizatora eventu przez admina
- Widok z formularzem zmiany właściciela koła przez admin
- Widok z formularzem utworzenia ankiety

Kryteria akceptacji: 

1. Widok zgodny z makietami 
2. Font oraz Icon jest responsywny 
~~3. Jeżeli jest to pozytywny wynik zmiany organizatora eventu i zmiany właściciela koła przez admina wówczas w~~ ~~komunikacie zawarta jest tytuł wydarzenia/kola oraz imię i nazwiska nowego oraz starego właściciela/organizatora~~ 
~~4. Jeżeli jest to pozytywny wynik utworzenia kola zainteresować lub eventu komunikat zawiera nazwę utworzonego~~ ~~eventu/koła, a button może przekierować do utworzonego eventu/koła~~
~~5. Jeżeli jest to pozytywny wynik dodania ankiety do wydarzenia komunikat zawiera nazwę ankiety oraz wydarzenia,~~ 
~~którego dotyczy, a button może przekierować do utworzonej ankiety~~
~~6. Jeżeli jest to negatywny wynik utworzenia kola zainteresować/eventu, dodania ankiety, zmiany organizatora lub~~ ~~właściciela to po wciśnięciu buttona użytkownik wraca do wcześniej wypełnianego formularza (wpisane wcześniej values~~  ~~resetują się)~~
3. Widok poprawnie wyświetla przekazane do niego dane
7. Kursor zmienia się na pointer po najechaniu na button (Kryterium dot. taska z buttonami),

**Comment by PawelJurga** [comment]
@abdevworks daj linka do tego widoku :)

**Comment by PawelJurga** [comment]
Task będzie do testowania po stworzeniu do niego widoku formularza.
