### ISSUE TITLE
[FE-2] Stworzenie buttonów prostokątnych

### ISSUE THREAD

**Issue by fbrv01** [akademia-envelo-3/MELO-front#3]
## Dodatkowe informacje:
Stworzenie przycisków zgodnie z makietami:
https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=316%3A7550&t=KxDA9HQmjSq2SnMU-4

## Kryteria akceptacji:
1. Zgodność z makietami.

**Comment by dominikapap** [comment]
Task dotyczy tylko przycisków prostokątnych, okrągłe są w osobnym tasku
