### ISSUE TITLE
[BUG][FRONT] Nieprawidłowe skalowanie widoku strony

### ISSUE THREAD

**Issue by PawelJurga** [akademia-envelo-3/MELO-front#33]
Priorytet
    **średni**
    

Środowisko/branch
 (https://deploy-preview-31--melo-envelo.netlify.app/)

Ścieżka odtworzenia
Na przeglądarce Firefox widok strony skaluję się niepoprawnie w trybie mobilnym oraz dla web.

- [ ]  **Oczekiwany rezultat : widok strony będzie dostosowany do standardów RWD**

**Comment by PawelJurga** [comment]
@dominikapap jak zrobisz poprawki to oznacz mnie do wykonania retestu :)

**Comment by dominikapap** [comment]
@PawelJurga prośba o potwierdzenie czy teraz jest ok :)

**Comment by dominikapap** [comment]
[aktualny link do podglądu](https://deploy-preview-35--melo-envelo.netlify.app/)

**Comment by PawelJurga** [comment]
- [x]  **Oczekiwany rezultat : widok strony będzie dostosowany do standardów RWD** 
Wynik retestu : **POZYTYWNY**
**zamykam zgłoszenie** :)
