### ISSUE TITLE
[ST-01] podmiana przycisku na stronie 404 

### ISSUE THREAD

**Issue by dominikapap** [akademia-envelo-3/MELO-front#38]
Na komponencie PageNotFound wprowadzony był tymczasowy wygląd przycisku. Należy zmienić przycisk na zgodny z makietą. 

### Makiety 
[mobile](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=454%3A9841&t=PojAXxbYIEKkm7Bq-0)
[desktop](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=457%3A9907&t=PojAXxbYIEKkm7Bq-0)

### Task blokujący
#32 

### Kryteria akceptacji

1. Wygląd  przycisku jest zgodny z makietami i z wzorem przycisku widocznym na podstronie theme
2. Przycisk po naciśnięciu przekierowuje na stronę główną

**Comment by fbrv01** [comment]
QA ok
- [x] wygląd zgodny z makietami
- [x] przycisk po naciśnięciu przekierowuje na stronę główną
