### ISSUE TITLE
[MKT-02] Zrobienie makiety szczegółowej dla widoku pola komentarza 

### ISSUE THREAD

**Issue by abdevworks** [akademia-envelo-3/MELO-front#42]
### Dodatkowe Informacje
Należy stworzyć w Figmie makietę szczegółową dla widoku pola do pisania komentarza zarówno dla widoku mobilnego jak i dużego ekranu.
### Makieta
[Wzór](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=775%3A9931&t=eauKrO8q1F5vm4UE-0)
### Kryteria Akceptacji
1. Makieta zawiera widok pola do pisania komentarzy dla dużego ekranu
2. Makieta zawiera widok pola do pisania komentarzy dla widoku mobilnego

**Comment by abdevworks** [comment]
Linki do gotowej makiety:
[Makieta 01](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=837%3A10616&t=eauKrO8q1F5vm4UE-0)
[Makieta 02](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=805%3A9933&t=eauKrO8q1F5vm4UE-0)
[Makieta 03](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=775%3A10027&t=eauKrO8q1F5vm4UE-0)
[Makieta 04](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=775%3A10187&t=eauKrO8q1F5vm4UE-0)

**Comment by PawelJurga** [comment]
- [x]   Makieta zawiera widok pola do pisania komentarzy dla dużego ekranu

   
- [x]  Makieta zawiera widok pola do pisania komentarzy dla widoku mobilnego



**Rekomenduję zakończenie taska :)**
