### ISSUE TITLE
[FE-22] Ustalenie DTO nowego koła

### ISSUE THREAD

**Issue by abdevworks** [akademia-envelo-3/MELO-front#47]
### Dodatkowe informacje
Należy stworzyć diagram DTO dla nowego koła. Diagram ten odnosi się do danych otrzymanych z formularza utworzenia nowego koła. Stworzony diagram dodać do dokumentu diagrams, zakładka DTO. Na podstawie tego diagramu dodać zmokowane dane koła to bazy db.json. 

1. [Link do projektu j-son server ze zmokowanymi danymi](https://github.com/LukaszStaniszewski/MeloJSONServer)
2. [Link do dokumentu diagrams](https://app.diagrams.net/#G1tlWXAN-YmH3q36eRUlPHq3PNlyLWVDaV)
3. [Makieta formularza tworzenia nowego koła](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=913%3A10667&t=wFubEuu6vVmKgmdq-0)

### Kryteria akceptacji
1. Diagram DTO koła został dodany do dokumentu diagrams w zakładce DTOs.
2. Diagram jest zgodny z dokumentacją projektu.
4. Dodano zmokowane dane do pliku db.json projektu z j-son server.

**Comment by dominikapap** [comment]
[DTO Koła](https://app.diagrams.net/#G1tlWXAN-YmH3q36eRUlPHq3PNlyLWVDaV)

**Comment by dominikapap** [comment]
Zmockowane dane w json-server mają postać taką jaką będziemy otrzymywali ostatecznie od backendu. Tworząc serwis do pobierania danych odnośnie kół zainteresowań należy stworzyć metody które zasymulują działanie backendu.

**Comment by fbrv01** [comment]
Jest ok.
