### ISSUE TITLE
[FE-24] Dodanie routingu

### ISSUE THREAD

**Issue by abdevworks** [akademia-envelo-3/MELO-front#50]
### Dodatkowe informacje
W ramach tego taska należy dodać do aplikacji podstawowy routing zgodny z ustaleniami.

### Podstawowa struktura routingu:
**Routing dla events**
[ "" ] - przekierowanie na /events
[ /events ]  - lista wszystkich eventów
[ /events/:id ] - szczegóły eventu
[ /events/new-event ] - widok tworzenia nowego eventu
[ /units ] - widok listy wszystkich kół
[ /units/new-unit ] - widok tworzenia nowego koła

**Routing dla loginu**
 [ /login ] - strona logowania 

**Routing dla admina**
[ /admin ] - przekierowuje na [ /admin/events ]
[ /admin/events  ] - wszystkie eventy 
[ /admin/units ] - wszystkie koła
[ /admin/hashtags ] - wszystkie hashtagi
[ /admin/hashtags/stats ] - statystyki hashtagów
[ /admin/hashtags/:id ] - wyświetla okno edycji wybranego hashtagu
[ /admin/categories ] - lista wszystkich kategorii
[ /admin/categories:/:id ] - wyświetla okno edycji wybranej k tegorii
[ /admin/inbox ] - wyświetla inbox admina
[ /admin/inbox/archive ] - wyświetla listę przeczytanych wiadomości

### Kryteria akceptacji
1. Utworzony routing jest zgony z treścią taska

**Comment by dominikapap** [comment]
Z racji iż nie można dodać ścieżki bez komponentu, referencja routingu została dodana w README
