### ISSUE TITLE
[MKT-03] Uszczegółowienie makiety admina odnośnie hashtagów

### ISSUE THREAD

**Issue by abdevworks** [akademia-envelo-3/MELO-front#54]
### Dodatkowe informacje
Należy stworzyć makietę szczegółową dla widoku hashtagów dla admina. Makieta ta składać się będzie z widoku wszystkich hashtagów, widoku statystyk dla hashtagów oraz widoku edycji hashtagu. Makieta ma przedstawiać zarówno wersję widoku dla desktop oraz mobile.

### Makiety
[Makieta 01](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=315%3A11675&t=wFubEuu6vVmKgmdq-0)
[Makieta 02](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=315%3A12295&t=wFubEuu6vVmKgmdq-0)
[Makieta 03](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=315%3A12295&t=wFubEuu6vVmKgmdq-0)

### Kryteria akceptacji
1. Została utworzona makieta szczegółowa dla widoku wszystkich hashtagów
2. Została utworzona makieta szczegółowa dla widoku statystyk hashtagów
3. Została utworzona makieta szczegółowa dla widoku edycji hashtagu

**Comment by dominikapap** [comment]
W wersji na mobile powinny być wszystkie szczegółowe makiety. Nie przenosiłam wszystkiego 1:1 na desktop tylko bardziej ogólne ułożenie elementów.
