### ISSUE TITLE
[MKT-05] Uszczegółowienie makiety admina odnośnie kategorii

### ISSUE THREAD

**Issue by abdevworks** [akademia-envelo-3/MELO-front#56]
### Dodatkowe informacje
Należy stworzyć makietę szczegółową dla widoku kategorii dla admina. Makieta ta składać się będzie z widoku wszystkich kategorii, widoku edycji kategorii oraz widoku dodania nowej kategorii. Makieta ma przedstawiać zarówno wersję widoku dla desktop oraz mobile.

### Makiety
[Makieta 01](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=333%3A8921&t=wFubEuu6vVmKgmdq-0)
[Makieta 02](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=333%3A8316&t=wFubEuu6vVmKgmdq-0)
[Makieta 03](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=394%3A8841&t=wFubEuu6vVmKgmdq-0)

### Kryteria akceptacji
1. Została utworzona makieta szczegółowa dla widoku wszystkich kategorii
2. Została utworzona makieta szczegółowa dla dodania nowej kategorii
3. Została utworzona makieta szczegółowa dla widoku edycji kategorii

**Comment by dominikapap** [comment]
W wersji na mobile powinny być wszystkie szczegółowe makiety. Nie przenosiłam wszystkiego 1:1 na desktop tylko bardziej ogólne ułożenie elementów.
