### ISSUE TITLE
[FE-5] Stworzenie searchbar w widoku eventów

### ISSUE THREAD

**Issue by rafalfuz** [akademia-envelo-3/MELO-front#6]
Jako użutkownik chciałbym widzieć searchbar na górze aplikacji.

Dodatkowe informacje:
Task dotyczy wyglądu searchbara, nie uwzględnia logiki autouzupełniania, filtrowania oraz sortowania.

Makiety:
https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=314%3A7330&t=9QKPyQeUefjAKfsJ-4

Taski blokujące:
-  #1 

Taski powiązane:
Sortowanie wyszukiwania za pomocą buttonów
Filtrowanie eventów

Kryteria akceptacji

1. Searchbar zawiera placeholder "Szukaj w MELO" oraz ikone lupy
2. Po kliknieciu w input jego style zmienia sie na focus
3. Po wpisaniu 1 znaku w prawej stronie inputa wyswietla sie ikona X do zresetowania wpisanej frazy
~~4. Po wpisaniu >2 znakow wyswietla sie lista z 4 buttonami do filtowania~~
4. Po wpisaniu 1 znaku wyswietla sie lista z 4 buttonami do filtowania
~~5. Po wpisaniu >2 znaków i zdezaktywowaniu inputa lista znika~~
5. Gdy input jest pusty lista znika
~~6. Wyniki wyszukiwania pojawiają się po wpisaniu 2 znaków~~
7. Po najechaniu kursorem na wynik wyszukiwania jego background zmienia się
8. Maksymalna ilość znaków do wyszukiwania = 80

**Comment by LukaszStaniszewski** [comment]
Dobrze byłoby stworzyć kolejny task i dodać w nim nawigacje po wynikach za pomocą strzałek.

**Comment by LukaszStaniszewski** [comment]
Przy breakpoincie 320px wg. makiet searchbar zajmuje około 70% ekranu, więc komponent powinien działać do 240px.  

![Image](https://user-images.githubusercontent.com/89972891/212857230-6a16f7cf-11a6-4639-8aeb-eccb6b3c4745.png)

**Comment by abdevworks** [comment]
@PawelJurga Prośba o przetestowanie.
https://fe-5-add-searchbar-in-events-view--melo-envelo.netlify.app/theme

**Comment by PawelJurga** [comment]
- [x]  Searchbar zawiera placeholder "Szukaj w MELO" oraz ikone lupy

    

- [x] Po kliknieciu w input jego style zmienia sie na focus

  

- [x] Po wpisaniu 1 znaku w prawej stronie inputa wyswietla sie ikona X do zresetowania wpisanej frazy

 - **po zresetowaniu inputa backspacem ikona X nie znika.**   
 

![Image](https://user-images.githubusercontent.com/121928858/214772249-85d06b48-786e-4f57-9fdd-104ecf304854.png)





   

- [x]  Po wpisaniu 1 znaku wyswietla sie lista z 4 buttonami do filtowania
- **w przypadku wyszukiwarki dla kół nie wyświetlają się buttony, czy tak ma być ?**


![Image](https://user-images.githubusercontent.com/121928858/214773678-d038efb4-adc4-4051-9f4c-8f53dd7c1b26.png)



   
    

- [x] Gdy input jest pusty lista znika

    

- [ ] Wyniki wyszukiwania pojawiają się po wpisaniu 2 znaków

- **u mnie wyniki pojawiają się po jednym znaku** 


![Image](https://user-images.githubusercontent.com/121928858/214772678-93f762b8-b471-4570-ba81-526b5520e9c4.png)



   

- [x]  Po najechaniu kursorem na wynik wyszukiwania jego background zmienia się

   

- [x]  Maksymalna ilość znaków do wyszukiwania = 80

**Comment by abdevworks** [comment]
https://github.com/akademia-envelo-3/MELO-front/issues/6#issuecomment-1404618872

- Po kliknięciu w input jego style zmienia się na focus - zmienia się kolor obramówki na żółty, może jest to słabo widoczne na jasnym tle

- Po wpisaniu 1 znaku wyswietla sie lista z 4 buttonami do filtowania

w przypadku wyszukiwarki dla kół nie wyświetlają się buttony, czy tak ma być ? - tak, tak miało być. koła są wyszukiwane jedynie po tekście
- Gdy input jest pusty lista znika - lista ma znikać jeśli nie jest nic wpisane
- Wyniki wyszukiwania pojawiają się po wpisaniu 2 znaków - Rafał zapomniał poprawić punkt 6 przy edycji kryteriów akceptacji. Miało być po jednym znaku.
- Po najechaniu kursorem na wynik wyszukiwania jego background zmienia się - tak, zgodnie z makietą miał się zmieniać
- Maksymalna ilość znaków do wyszukiwania = 80 - nie bardzo rozumiem dlaczego jest tutaj ten punkt, skoro można wpisać jedynie 80 znaków

@PawelJurga

**Comment by PawelJurga** [comment]
**Retest**
**W nawiązaniu do komentarza powyżej do retestu był brany tylko jeden błąd** . Reszta działała poprawnie (zapomniałem odznaczyć checkboxy).
_Po zresetowaniu inputa backspacem ikona X nie znika_ - **wynik pozytywny, ikona X znika po usunięciu inputa**

**Rekomenduję zakończenie taska :)**
