### ISSUE TITLE
[FE-6] Stworzenie navbara

### ISSUE THREAD

**Issue by fbrv01** [akademia-envelo-3/MELO-front#7]
### Story 
Jako użytkownik korzystam ze strony w wygodny sposób korzystając z navbara. 

### Dodatkowe Informacje
Na tym etapie nie uwzględniamy routingu.

### Taski powiązane
- #9 

### Taski blokujące
- #6 

### Makiety 
1. [desktop](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=309%3A8005&t=eQjPc9rwQb9fXaBQ-4)
2. [mobile](https://www.figma.com/file/ybxNkntmTWg7yLBzHhBx4R/MELO?node-id=372%3A8759&t=eQjPc9rwQb9fXaBQ-4)

### Kryteria akceptacji
1. Zgodność z makietami.
2. Responsywność m.in. z obsługiwanymi przez aplikację breakpointami.

**Comment by LukaszStaniszewski** [comment]
Na mobilnym nie jest zgodny z makietami, za mały padding, zbyt duży rozmiar navbara - na mobilnych miał być mniejszy

![Image](https://user-images.githubusercontent.com/89972891/215459632-84dc2de6-31bc-4c3b-927b-e62a5d2f0425.png)

**Comment by LukaszStaniszewski** [comment]
Według makiet dzwonek ma mieć większy odstęp od prawej strony. Dodałbym również lepsze wycentrowanie dzwonka i loga.

![Image](https://user-images.githubusercontent.com/89972891/215460244-f8b155fb-8c31-4262-924d-9d9c04aae7e5.png)


![Image](https://user-images.githubusercontent.com/89972891/215462136-6d1ed954-b377-4581-9c0e-ac97bf52a796.png)

**Comment by rafalfuz** [comment]
Pomniejszony dla widoku mobile, dzwonek przesunety bardziej od prawej strony
