### ISSUE TITLE
[FE-30] Zmiana wielkosci dla power Icons

### ISSUE THREAD

**Issue by rafalfuz** [akademia-envelo-3/MELO-front#71]

**Comment by rafalfuz** [comment]
Należ stworzyć mniejszy rozmiar dla power icons

Taski powiązane
#14 
Kryteria akceptacji:
1. Power Icon pasuje wielkością do rozmiaru karty eventu
2. Zawartość icony nie wychodzi poza obszar kola

**Comment by dominikapap** [comment]
[Preview](https://fe-30-resize-power-con--melo-envelo.netlify.app/theme)

**Comment by dominikapap** [comment]
@rafalfuz prośba o uszczegółowienie kryterium akceptacji : Power Icon pasuje wielkością do rozmiaru karty eventu. Czy chodzi o to, że rozmiar jest zgodny z makietą? na podglądzie nie ma karty eventu żeby sprawdzić jak power icon się w niej zachowuje.

**Comment by fbrv01** [comment]
bez nalozenia ikony na karte eventu nie da sie tego sprawdzic chyba?

**Comment by rafalfuz** [comment]
Szczerze przyznam, ze task był pisany na szybko, głownie dlatego, aby stworzyć tylko gałąź do przebudowy buttona. Rozmiar został już zmniejszony na zmiennej globalnej o około 25% wiec wzorem pierwotnym powinien wielkością być odpowiedni dla karty eventu.

**Comment by dominikapap** [comment]
@rafalfuz  można mergować
